### ISSUE TITLE
encoding error with arabic chars

### ISSUE THREAD

**Issue by HamidDevelop** [qtwyeuritoiy/Centipede#1]
hi dear.now code runs correct but for conversations with arabic language have problem.i get this error:

  File "crawler.py", line 75, in run
    self.write_to_file(messages)
  File "crawler.py", line 60, in write_to_file
    output.write(sender_id+": ["+message.replace("\n", "\\n")+"]\n")
  File "C:\Python36\lib\encodings\cp1256.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 6-9: cha
racter maps to <undefined>

**Comment by qtwyeuritoiy** [comment]
Hi hamid,

I saved some random arabic texts and had no problems. The problem seems like it's a problem of Windows. see https://stackoverflow.com/a/16347188 for more info.
